### ISSUE TITLE
Custom intermediate steps drop down is not showing up

### ISSUE THREAD

**Issue by ssling0817** [NVIDIA/NeMo-Agent-Toolkit#383]
I included CUSTOM_START and CUSTOM_END in custom_event_types and added the following code in the workflow, but the CUSTOM_START and CUSTOM_END only showed up in phoenix trace and not in the UI dropdown.

config:
```
general:
  use_uvloop: true
  telemetry:
    logging:
      console:
        _type: console
        level: WARN
    tracing:
        phoenix:
          _type: phoenix
          endpoint: ...

  front_end:
    _type: fastapi
    host: "0.0.0.0"
    cors:
      allow_origins: ["http://localhost:3000"]
      allow_headers: ["*"]
      allow_methods: ["*"]
    step_adaptor:
      mode: custom
      custom_event_types: [CUSTOM_START, CUSTOM_END, LLM_START, LLM_END, TOOL_START, TOOL_END, FUNCTION_START, FUNCTION_END]
```

workflow:

```
...
class CustomIntermediateStepPayload(IntermediateStepPayload):
    UUID: str = Field(default_factory=lambda: str(uuid.uuid4()), description="UUID")
    name: str|None = Field(default="", description="Tool name")  
    data: StreamEventData|None = Field(default_factory=StreamEventData, description="Data")  
    event_type: IntermediateStepType = Field(default=IntermediateStepType.CUSTOM_START)

class CustomIntermediateStepPayloadEnd(IntermediateStepPayload):
    UUID: str = Field(default_factory=lambda: str(uuid.uuid4()), description="UUID")
    name: str|None = Field(default="", description="Tool name")
    data: StreamEventData|None = Field(default_factory=StreamEventData, description="Data")
    event_type: IntermediateStepType = Field(default=IntermediateStepType.CUSTOM_END)
def custom_start_tool(step_manager: IntermediateStepManager,
                      name: str,
                      input_data: typing.Any | None = None,
                      output_data: typing.Any | None = None):
    uid = str(uuid.uuid4())
    start_step = CustomIntermediateStepPayload(UUID=uid,
                                               name=name,
                                               data=StreamEventData(input=input_data, output=output_data),
                                               event_type=IntermediateStepType.CUSTOM_START)
    step_manager.push_intermediate_step(start_step)

    return uid


def custom_end_tool(step_manager: IntermediateStepManager,
                    uid: str,
                    name: str,
                    input_data: typing.Any | None = None,
                    output_data: typing.Any | None = None):

    end_step = CustomIntermediateStepPayloadEnd(UUID=uid,
                                                name=name,
                                                data=StreamEventData(input=input_data, output=output_data),
                                                event_type=IntermediateStepType.CUSTOM_END)
    step_manager.push_intermediate_step(end_step)
...
step_manager = AIQContext.get().intermediate_step_manager
if step_manager is not None:
                uid = custom_start_tool(step_manager=step_manager, name="genie_log", input_data=s_df)
                custom_end_tool(step_manager=step_manager, uid=uid, name="genie_log", output_data=sql_query) 
```
