### ISSUE TITLE
[FEA]: Latency in the weave eval dashboard

### ISSUE THREAD

**Issue by AnuradhaKaruppiah** [NVIDIA/NeMo-Agent-Toolkit#388]
### Is this a new feature, an improvement, or a change to existing functionality?

New Feature

### How would you describe the priority of this feature request

Critical (currently preventing usage)

### Please provide a clear description of problem this feature solves

To run prompt-tuning or model-change experiments developers need to compare multiple evaluation dimensions simultaneously;  accuracy vs. latency vs. tokens are typical comparison dimensions. 
1. The weave "eval panel" is missing latency dimension in both the "Summary" and "Dataset results" tab.
2. "Dataset results" tab is not showing all the entries in the plot. I have 7 rows in the dataset corresponding to the attached plot.

![Image](https://github.com/user-attachments/assets/4e5acadc-d4e0-4f44-93e4-c60345d3010b)

![Image](https://github.com/user-attachments/assets/2458d8b5-4e77-4c35-810f-3ee2dbb4beab)

### Describe your ideal solution

Latency (for tool and LLM calls) and token usage stats are available in the intermediate steps and can be viewed as a json file today. For the two runs (images attached above) here are stats pulled from the intermediate steps (see src/aiq/profiler/ProfilerRunner for details) -
Run-1:
```
  "workflow_runtimes": {
    "p90": 23.47574315071106,
    "p95": 23.615864324569703,
    "p99": 23.727961263656617
  }
```
Run-2:
```
  "workflow_runtimes": {
    "p90": 72.50402975082397,
    "p95": 75.31011748313904,
    "p99": 77.55498766899109
  }
```
I used the following eval configuration to enable profiler computations:
```
eval:
  general:
    output_dir: .tmp/aiq/examples/alert_triage_agent/output/llama_31/
    dataset:
      _type: json
      file_path: examples/alert_triage_agent/data/offline_data.json
    profiler:
      token_uniqueness_forecast: true
      workflow_runtime_forecast: true
      compute_llm_metrics: true
      csv_exclude_io_text: true
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I have searched the [open feature requests](https://github.com/NVIDIA/NeMo-Agent-Toolkit/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22%2Cimprovement%2Cenhancement) and have found no duplicates for this feature request
